### ISSUE TITLE
ModuleNotFoundError: No module named 'efficientnet_pytorch'

### ISSUE THREAD

**Issue by molyswu** [kentaroy47/efficientdet.pytorch#3]
File "train_efficientdet.py", line 111, in <module>
    from utils.efficientdet import EfficientDet
  File "/EfficientDet/efficientdet.pytorch/utils/efficientdet.py", line 1, in <module>
    from efficientnet_pytorch import EfficientNet
ModuleNotFoundError: No module named 'efficientnet_pytorch'

Thanks!

**Comment by kentaroy47** [comment]
please install efficientnet
`pip install --upgrade efficientnet-pytorch`
thanks!
